#!/bin/sh

protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

exec < /dev/tty

PUSH_PROMPT="You're about to push master, is that what you intended? [y|n] "
if [ "$protected_branch" = "$current_branch" ]
then
    if command -v cowsay >/dev/null
    then
      cowsay "$PUSH_PROMPT"
    else
      printf "\n***************************************************************\n"
      printf "%s\n", "$PUSH_PROMPT"
      printf  "***************************************************************\n"
    fi
    read -p "" REPLY
    if echo "$REPLY" | grep -E '^[Yy]$' > /dev/null
    then
        exit 0 # push will execute
    fi
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi
